title: "Marmorstein Lab"
email: marmor@upenn.edu
description: >-
  Research in the Marmorstein Lab focuses on epigenetics, chromatin regulation,
  protein acetylation and acetyl-CoA metabolism, and MAPK signaling. 
  We use structural biology, biochemical, and chemical biology approaches.
baseurl: "" 
url: "https://JeffZ97.github.io/marmorstein-lab"
github_username: JeffZ97

# Social links
scholar: "https://scholar.google.com/citations?user=XXXX" # Replace with PI's Google Scholar
orcid: "https://orcid.org/XXXX" # Replace with PI's ORCID
linkedin: ""
twitter: ""

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
